# Generated by Django 4.2.7 on 2025-05-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_available_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='aave',
            new_name='total_gain',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ada',
            new_name='total_invested',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bch',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bnb',
        ),
        migrations.RemoveField(
            model_name='account',
            name='btc',
        ),
        migrations.RemoveField(
            model_name='account',
            name='eth',
        ),
        migrations.RemoveField(
            model_name='account',
            name='link',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ltc',
        ),
        migrations.RemoveField(
            model_name='account',
            name='usdt',
        ),
        migrations.RemoveField(
            model_name='account',
            name='xlm',
        ),
        migrations.RemoveField(
            model_name='account',
            name='xrp',
        ),
    ]
