# Generated by Django 4.2.7 on 2025-06-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='crypto',
        ),
        migrations.RemoveField(
            model_name='account',
            name='realestate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='retirement',
        ),
        migrations.RemoveField(
            model_name='account',
            name='stock',
        ),
    ]
