# Generated by Django 4.2.7 on 2026-02-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='plan',
            field=models.CharField(max_length=255),
        ),
    ]
