# Generated by Django 4.2.7 on 2025-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptochannel',
            name='qrcode_image',
            field=models.ImageField(upload_to='crypto'),
        ),
    ]
