# Generated by Django 4.2.7 on 2025-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_cryptochannel_qrcode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('roi', models.IntegerField()),
                ('icon', models.ImageField(upload_to='icon')),
            ],
        ),
    ]
