# Generated by Django 4.2.7 on 2025-05-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_investmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptochannel',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
