# Generated by Django 4.2.7 on 2025-05-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_cryptochannel_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptochannel',
            name='label',
            field=models.CharField(default='hello', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
