# Generated by Django 4.2.7 on 2025-05-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_cryptochannel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptochannel',
            name='label',
            field=models.CharField(max_length=15),
        ),
    ]
