# Generated by Django 4.2.7 on 2025-05-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_cryptochannel_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptochannel',
            name='label',
        ),
    ]
