# Generated by Django 4.2.7 on 2025-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_remove_cryptochannel_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptochannel',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
