# Generated by Django 4.2.7 on 2025-05-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_alter_cryptochannel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('facebook_url', models.URLField()),
                ('telegram_url', models.URLField()),
                ('twitter_url', models.URLField()),
            ],
        ),
    ]
