# Generated by Django 4.2.7 on 2025-07-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_supportchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='roi',
            field=models.FloatField(),
        ),
    ]
