# Generated by Django 4.2.7 on 2025-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('type', models.CharField(choices=[('withdraw', 'Withdrawal'), ('deposit', 'Deposit')], max_length=15)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(max_length=15)),
                ('wallet_address', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
