# Generated by Django 4.2.7 on 2025-05-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('withdraw', 'Withdrawal'), ('deposit', 'Deposit'), ('realestate', 'Real Estate'), ('stock', 'Stock'), ('crypto', 'Cryptocurrency'), ('retirement', 'Retirement')], max_length=15),
        ),
    ]
