# Generated by Django 4.2.7 on 2025-05-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='network',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
