# Generated by Django 4.2.7 on 2026-02-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_transaction_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='network',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('withdraw', 'Withdrawal'), ('deposit', 'Deposit'), ('realestate', 'Real Estate'), ('stock', 'Stock'), ('crypto', 'Cryptocurrency'), ('retirement', 'Retirement')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
