# Generated by Django 4.2.7 on 2025-05-25 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('validity_period', models.CharField(max_length=50)),
                ('reason_for_visit', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100)),
                ('to_city', models.CharField(max_length=100)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('boarding_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first-class', 'First Class')], default='economy', max_length=20)),
                ('trip_type', models.CharField(choices=[('oneway', 'One Way'), ('return', 'Round Trip'), ('multi', 'Multi City')], default='oneway', max_length=20)),
                ('passenger', models.IntegerField(default=1)),
                ('flight_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
