# Generated by Django 4.2.7 on 2025-05-25 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visa',
            old_name='validity_period',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='visa',
            old_name='reason_for_visit',
            new_name='reason',
        ),
        migrations.AddField(
            model_name='visa',
            name='nationality',
            field=models.CharField(default='Nigeria', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visa',
            name='travel_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 22, 17, 56, 178782, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visa',
            name='visa_type',
            field=models.CharField(choices=[('tourist', 'Tourist'), ('student', 'Student'), ('work', 'Work')], max_length=50),
        ),
    ]
