# Generated by Django 4.2.7 on 2025-05-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_otp_code_customuser_otp_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pics',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
