# Generated by Django 4.2.7 on 2025-05-19 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_residence', models.CharField(max_length=200)),
                ('middlename', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
                ('postal', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('selfie', models.ImageField(upload_to='verifications/people')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('driving_licence', 'Driving Licence'), ('national_id_card', 'National Identity Card')], max_length=30)),
                ('image', models.ImageField(upload_to='verifications/ID/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
