# Generated by Django 4.2.7 on 2025-05-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userverification_idverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='lastname',
            field=models.CharField(default='u', max_length=50),
            preserve_default=False,
        ),
    ]
