# Generated by Django 4.2.7 on 2025-05-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userverification_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idverification',
            name='id_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('licence', 'Driving Licence'), ('card', 'Government Issued Card')], max_length=30),
        ),
    ]
