# Generated by Django 4.2.7 on 2025-05-24 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_idverification_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('spouse', 'Spouse'), ('child', 'Child'), ('friend', 'Friend'), ('other', 'Other')], max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nextofkin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
