# Generated by Django 4.2.7 on 2025-05-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_idverification_status_userverification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_verify',
            field=models.BooleanField(default=False),
        ),
    ]
