# Generated by Django 4.2.7 on 2025-05-26 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_userverification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tier3', to=settings.AUTH_USER_MODEL),
        ),
    ]
