# Generated by Django 4.2.7 on 2025-05-13 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='start_date',
        ),
    ]
